# Generated by Django 4.1.4 on 2022-12-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='task',
            field=models.TextField(blank=True, null=True),
        ),
    ]
